default: &default
  address:              smtp.gmail.com
  port:                 587
  domain:               whitneyhome.com
  user_name:            russ@whitneyhome.com
  password:             Marflon43
  authentication:       plain
  enable_starttls_auto: true

development:
  <<: *default

production:
  address:              locahost
  port:                 25
  domain:               mcaems.org
